### PR TITLE
fix: Participants Are Only Mentioned - MEED-2689 - Meeds-io/meeds#1168

### LINKED ISSUE #1168: [Task] mention non members from general task app
**Steps to reproduce**

1. Go to general task app /portal/meeds/tasks
2. Access a task project related to a space
3. Access a task and add a comment
4. Mention users
5. See error: non members / non participants can be mentioned

**Expected behavior**

Only participants can be mentioned and assigned

### PR DESCRIPTION
**Pull request by sergeByishimo**
Prior to this change non members / non participants of a task project related to a space, can be mentioned while adding a task comment in the general task app /portal/meeds/tasks. This change will make sure only project participants can be mentioned in the general task app.

### CODE REVIEW

File: webapps/src/main/webapp/vue-app/taskCommentsDrawer/components/TaskCommentEditor.vue [hunk 1]
```diff
@@ -31,6 +31,7 @@
         :placeholder="placeholder"
         :object-id="newCommentId"
         :tag-enabled="false"
+        :suggester-space-url="getSpaceUrlFromProjectParticipator()"
```
Comment (boubaker) [inline webapps/src/main/webapp/vue-app/taskCommentsDrawer/components/TaskCommentEditor.vue]: Please add it as computed value instead of a method

```suggestion
        :suggester-space-url="taskSpaceUrl"
```

File: webapps/src/main/webapp/vue-app/taskCommentsDrawer/components/TaskCommentEditor.vue [hunk 2]
```diff
@@ -199,6 +200,15 @@ export default {
...
     },
+    getSpaceUrlFromProjectParticipator() {
+      const participator = this.task.status.project.participator;
+      if (participator && participator.length > 0) {
+        const projectParticipator = participator.find((element) => element.startsWith('member:/spaces/'));
+        if (projectParticipator) {
+          return projectParticipator.substring(15);
+        }
+      }
+    },
```
Comment (boubaker) [inline webapps/src/main/webapp/vue-app/taskCommentsDrawer/components/TaskCommentEditor.vue]: Please add the variable into a computed and you can test in `/space/` only without `member:` to allow better extensibility and maintainability (by example, when we add `*:/spaces/XYZ` instead of `member:/spaces/XYZ`, this should work as well)

Besides, in the proposed change, we will avoid a Null Pointer Exception when the task isn't added to a project yet.

```suggestion
    computed: {
      taskSpaceUrl() {
        const projectMembers = this.task?.status?.project?.participator;
        if (projectMembers?.length) {
          const projectSpace = projectMembers.find(member => member.includes('/spaces/'));
          if (projectSpace) {
            return projectSpace.split('/spaces/')[1];
          }
        }
        return null;
      },
    }
```

**Review by boubaker — COMMENTED** [review]
Thanks for your contribution and good catch !

File: webapps/src/main/webapp/vue-app/taskCommentsDrawer/components/TaskCommentEditor.vue (hunk 2 above)
Comment (sergeByishimo) [reply webapps/src/main/webapp/vue-app/taskCommentsDrawer/components/TaskCommentEditor.vue]: Thanks for the feedback. Working on it.

**Comment by sergeByishimo** [comment]
This pull request is also dependent on this small fix on `social` being approved Meeds-io/social#3040

**Comment by boubaker** [comment]
> This pull request is also dependent on this small fix on `social` being approved [Meeds-io/social#3040](https://github.com/Meeds-io/social/pull/3040)

That's a nice enhancement indeed. But knowing that we shouldn't introduce a breaking change on Common UI components, is it possible to revert the `social` PR and use here the variable with `suggester-space-u-r-l` instead. In fact, if we apply the `social` PR, there will be regressions in other modules in Meeds (see https://github.com/Meeds-io/kudos/blob/develop/kudos-webapps/src/main/webapp/vue-app/kudos/components/KudosApp.vue#L185).

We may need to split the concerns, WDYT ? (I let you choose to create another PR for the camel case fix on kudos module or simplify the fix in this PR by closing social PR).

**Comment by sergeByishimo** [comment]
> we shouldn't introduce a breaking change on Common UI components

We shouldn't indeed without thinking of all implications on other modules. I also found that it would affect [this activity composer drawer](https://github.com/Meeds-io/social/blob/develop/webapp/portlet/src/main/webapp/vue-apps/activity-stream/components/toolbar/ActivityComposerDrawer.vue#L126C26-L126C26).

Let me simply use here the variable with `suggester-space-u-r-l` and close the `social` PR.

Thanks for the feedback.

**Comment by boubaker** [comment]
Thanks @sergeByishimo for your contribution.
We will proceed on testing the modification and get back to you shortly.

( BTW, you can even contribute on automatic UI tests using a **Cucumber** & **Serenity** that you can propose [here](https://github.com/meeds-io/meeds-qa-auto) to prove the fix )

**Review by boubaker — APPROVED** [review]
